### PR TITLE
Update docker-compose.yaml with infos about local run

### PR DESCRIPTION
**Pull request by andreas-bauer**

### CODE REVIEW

**Comment by andreas-bauer** [comment]
To run it locally use:
`docker compose up`

To run in in the prod environment use:
`docker compose -f docker-compose.yaml -f docker-compose.prod.yaml up`

**Comment by andreas-bauer** [comment]
@waleedabdeen 👀

**Comment by andreas-bauer** [comment]
@waleedabdeen 👀

**Comment by andreas-bauer** [comment]
@waleedabdeen ?

**Comment by michaeldorner** [comment]
@waleedabdeen 
giphy

**Comment by waleedabdeen** [comment]
I am testing now @michaeldorner  and @andreas-bauer

**Comment by waleedabdeen** [comment]
@andreas-bauer 
Still having the same issue the docker container is using the server backend which is not suppose to be the case for development environment. Here are the steps to reproduce:

1. cd to MiCRA directory
2. `docker-compose down`
3. `docker remove CONTAINER_ID` (for both backend and frontend)
4. `docker-compose up`

docker_bug

**Comment by andreas-bauer** [comment]
@waleedabdeen I don't have these problems.

Try to rebuild the frontend without using the cache:

```
docker compose build frontend --no-cache
```

Screenshot 2024-03-05 at 15 35 26

**Comment by waleedabdeen** [comment]
Fixed with `docker-compose up -d --no-deps --build`

**Pull request merged**
